SUCCESS = 200

REDIRECT_REQUEST = 303

BAD_REQUEST = 400
NOT_AUTHORIZED_ERROR = 401
NOT_FOUND = 404
NOT_ACCEPTABLE = 406

INTERNAL_SERVER_ERROR = 500

class ErrorMessages:
    USER_NOT_LOGGED_IN = 'User Not Logged In'
    INVALID_SESSION = 'Invalid Session'