#!/usr/bin/env python3

import sys
import psycopg2 as psql

db_uri = sys.argv[1]
db_connection = psql.connect(db_uri)
cursor = db_connection.cursor()

cursor.execute('SELECT COUNT(id) FROM subposition')
count, = cursor.fetchone()
if count > 0:
	sys.exit(0)
try:
	print('Restoring Table: subposition')
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (2, 2, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (3, 3, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (4, 4, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (5, 5, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (6, 6, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (7, 7, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (8, 8, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (9, 9, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (10, 10, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (11, 11, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (12, 12, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (13, 13, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (14, 14, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (15, 15, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (16, 16, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (17, 17, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (18, 18, 'Neutral')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (19, 2, 'Speed')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (20, 2, 'Passer')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (21, 3, 'Speed')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (22, 3, 'Power')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (23, 4, 'Blocking')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (24, 4, 'Receiving')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (25, 5, 'Speed')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (26, 5, 'Possession')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (27, 6, 'Run Blocker')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (28, 6, 'Pass Blocker')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (29, 7, 'Run Blocker')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (30, 7, 'Pass Blocker')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (31, 8, 'Run Blocker')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (32, 8, 'Pass Blocker')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (33, 9, 'Blocking')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (34, 9, 'Receiving')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (35, 10, 'Coverage')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (36, 10, 'Hard Hitter')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (37, 11, 'Coverage')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (38, 11, 'Hard Hitter')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (40, 12, 'Coverage')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (41, 12, 'Hard Hitter')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (42, 13, 'Coverage')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (43, 13, 'Run Stopper')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (44, 14, 'Coverage')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (45, 14, 'Run Stopper')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (46, 15, 'Pass Rusher')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (47, 15, 'Run Rusher')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (48, 16, 'Pass Rusher')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (49, 16, 'Run Rusher')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (50, 17, 'Power')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (51, 17, 'Accuracy')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (52, 18, 'Power')")
	cursor.execute("INSERT INTO subposition (id,parent_position_id,name) VALUES (53, 18, 'Accuracy')")
	cursor.execute("ALTER SEQUENCE subposition_id_seq RESTART WITH 53")
	db_connection.commit()
	print('Restored Table: subposition Succesfully')
except:
	sys.exit(1)
cursor.close()
db_connection.close()

